// Generated by Android Localization Generator
// DO NOT EDIT THIS FILE MANUALLY

package com.localization

import android.content.Context
import androidx.annotation.StringRes

/**
 * Generated localization class for Android
 * Provides type-safe access to localized strings
 */
object Localization {
    
    // MARK: - Common
    object Common {
        object Buttons {
            @StringRes
            fun save(context: Context): String = context.getString(R.string.common_buttons_save)
            
            @StringRes
            fun cancel(context: Context): String = context.getString(R.string.common_buttons_cancel)
            
            @StringRes
            fun delete(context: Context): String = context.getString(R.string.common_buttons_delete)
            
            @StringRes
            fun edit(context: Context): String = context.getString(R.string.common_buttons_edit)
            
            @StringRes
            fun done(context: Context): String = context.getString(R.string.common_buttons_done)
            
            @StringRes
            fun back(context: Context): String = context.getString(R.string.common_buttons_back)
            
            @StringRes
            fun next(context: Context): String = context.getString(R.string.common_buttons_next)
            
            @StringRes
            fun previous(context: Context): String = context.getString(R.string.common_buttons_previous)
            
            @StringRes
            fun close(context: Context): String = context.getString(R.string.common_buttons_close)
            
            @StringRes
            fun ok(context: Context): String = context.getString(R.string.common_buttons_ok)
            
            @StringRes
            fun yes(context: Context): String = context.getString(R.string.common_buttons_yes)
            
            @StringRes
            fun no(context: Context): String = context.getString(R.string.common_buttons_no)
            
            @StringRes
            fun retry(context: Context): String = context.getString(R.string.common_buttons_retry)
            
            @StringRes
            fun refresh(context: Context): String = context.getString(R.string.common_buttons_refresh)
            
            @StringRes
            fun search(context: Context): String = context.getString(R.string.common_buttons_search)
            
            @StringRes
            fun filter(context: Context): String = context.getString(R.string.common_buttons_filter)
            
            @StringRes
            fun sort(context: Context): String = context.getString(R.string.common_buttons_sort)
            
            @StringRes
            fun share(context: Context): String = context.getString(R.string.common_buttons_share)
            
            @StringRes
            fun copy(context: Context): String = context.getString(R.string.common_buttons_copy)
            
            @StringRes
            fun paste(context: Context): String = context.getString(R.string.common_buttons_paste)
            
            @StringRes
            fun cut(context: Context): String = context.getString(R.string.common_buttons_cut)
            
            @StringRes
            fun undo(context: Context): String = context.getString(R.string.common_buttons_undo)
            
            @StringRes
            fun redo(context: Context): String = context.getString(R.string.common_buttons_redo)
        }
        
        object Messages {
            @StringRes
            fun loading(context: Context): String = context.getString(R.string.common_messages_loading)
            
            @StringRes
            fun error(context: Context): String = context.getString(R.string.common_messages_error)
            
            @StringRes
            fun success(context: Context): String = context.getString(R.string.common_messages_success)
            
            @StringRes
            fun warning(context: Context): String = context.getString(R.string.common_messages_warning)
            
            @StringRes
            fun info(context: Context): String = context.getString(R.string.common_messages_info)
            
            @StringRes
            fun confirmation(context: Context): String = context.getString(R.string.common_messages_confirmation)
            
            @StringRes
            fun noData(context: Context): String = context.getString(R.string.common_messages_no_data)
            
            @StringRes
            fun noResults(context: Context): String = context.getString(R.string.common_messages_no_results)
            
            @StringRes
            fun tryAgain(context: Context): String = context.getString(R.string.common_messages_try_again)
            
            @StringRes
            fun networkError(context: Context): String = context.getString(R.string.common_messages_network_error)
            
            @StringRes
            fun serverError(context: Context): String = context.getString(R.string.common_messages_server_error)
            
            @StringRes
            fun unknownError(context: Context): String = context.getString(R.string.common_messages_unknown_error)
        }
    }
    
    // MARK: - Android Specific
    object Android {
        object Navigation {
            object BottomNavigation {
                @StringRes
                fun home(context: Context): String = context.getString(R.string.android_navigation_bottom_navigation_home)
                
                @StringRes
                fun search(context: Context): String = context.getString(R.string.android_navigation_bottom_navigation_search)
                
                @StringRes
                fun favorites(context: Context): String = context.getString(R.string.android_navigation_bottom_navigation_favorites)
                
                @StringRes
                fun profile(context: Context): String = context.getString(R.string.android_navigation_bottom_navigation_profile)
                
                @StringRes
                fun more(context: Context): String = context.getString(R.string.android_navigation_bottom_navigation_more)
            }
        }
        
        object Gestures {
            @StringRes
            fun swipeRefresh(context: Context): String = context.getString(R.string.android_gestures_swipe_refresh)
            
            @StringRes
            fun swipeToDismiss(context: Context): String = context.getString(R.string.android_gestures_swipe_to_dismiss)
            
            @StringRes
            fun longPressContext(context: Context): String = context.getString(R.string.android_gestures_long_press_context)
            
            @StringRes
            fun doubleTapZoom(context: Context): String = context.getString(R.string.android_gestures_double_tap_zoom)
            
            @StringRes
            fun pinchZoom(context: Context): String = context.getString(R.string.android_gestures_pinch_zoom)
            
            @StringRes
            fun dragToReorder(context: Context): String = context.getString(R.string.android_gestures_drag_to_reorder)
        }
    }
}
